# P4Spec.ps1 -- Perforce change-spec construction for the installer.
#
# Extracted from install.ps1 so the two properties that matter can be asserted by
# tests without performing a real write install (see run-p4spec-tests.ps1). Both
# properties are things the installer previously got WRONG:
#
#   1. NO `Files:` section. `p4 change -o` (the new-changelist form) pre-fills
#      Files: with EVERY file currently open in the default changelist, so
#      building a new CL from it silently drags the user's unrelated work in.
#      A spec that never mentions Files: cannot do that.
#
#   2. NO UTF-8 BOM. Piping a spec into `p4 change -i` from PowerShell prepends a
#      BOM and p4 rejects the whole spec with `Unknown field name`. We write the
#      bytes ourselves with a BOM-less encoder and let the caller redirect the
#      file in via `cmd /c` -- PowerShell has no working `<` operator.
#
# Description lines in a change spec are TAB-indented; the blank separator lines
# must be a bare tab, not an empty line, or p4 truncates the description there.

Set-StrictMode -Version Latest

function New-P4ChangeSpecText {
    <#
    .SYNOPSIS
        Build the text of a `p4 change -i` spec for a brand-new, empty changelist.
    .OUTPUTS
        [string] spec text, LF-joined, with no Files: section.
    #>
    param(
        [Parameter(Mandatory=$true)] [string] $TagPrefix,
        [Parameter(Mandatory=$true)] [string] $ScriptVersion,
        [Parameter(Mandatory=$true)] [int]    $FileCount
    )

    $body = @(
        "$TagPrefix Agentic scaffolding - install -Mode Write phase",
        "",
        "## What",
        "- install.ps1 v$ScriptVersion writing $FileCount file(s) per package manifest.",
        "",
        "## Why",
        "- Apply current package templates/overlays to the consuming project.",
        "",
        "## Notes",
        "- Generated by install.ps1. Manually verify diff before submit."
    )

    $lines = @('Change: new', '', 'Description:')
    foreach ($b in $body) {
        # A bare tab keeps blank lines inside the Description field.
        if ([string]::IsNullOrEmpty($b)) { $lines += "`t" } else { $lines += "`t$b" }
    }
    return ($lines -join "`n")
}

function Write-P4SpecFile {
    <#
    .SYNOPSIS
        Write spec text as UTF-8 WITHOUT a BOM, for `p4 change -i < <file>`.
    #>
    param(
        [Parameter(Mandatory=$true)] [string] $Path,
        [Parameter(Mandatory=$true)] [string] $Text
    )
    [System.IO.File]::WriteAllText($Path, $Text, [System.Text.UTF8Encoding]::new($false))
}
